SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_MAX_LIVES = 3
PLAYER_INVULNERABILITY_TIME = 2.0  # seconds after respawn

SHOT_RADIUS = 5

# Score system
SCORE_SMALL_ASTEROID = 100
SCORE_MEDIUM_ASTEROID = 50
SCORE_LARGE_ASTEROID = 20

# Power-ups
POWERUP_RADIUS = 15
POWERUP_SPAWN_CHANCE = 0.3  # 30% chance when asteroid dies
POWERUP_DURATION = 5.0  # seconds
POWERUP_SPEED = 50

# Particle effects
PARTICLE_LIFETIME = 1.0  # seconds
PARTICLE_COUNT = 10

# Level system
LEVEL_ASTEROID_INCREASE = 0.1  # 10% faster spawn rate per level
LEVEL_SCORE_THRESHOLD = 500  # points needed for next level
